# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Social_Dis_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        MainWindow.setStatusTip("")

        # Choose One Title
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChooseTitle = QtWidgets.QLabel(self.centralwidget)
        self.ChooseTitle.setGeometry(QtCore.QRect(240, 95, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.ChooseTitle.setFont(font)
        self.ChooseTitle.setObjectName("ChooseTitle")

        #Webcam Option
        self.WebCam = QtWidgets.QRadioButton(self.centralwidget)
        self.WebCam.setGeometry(QtCore.QRect(240, 140, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.WebCam.setFont(font)
        self.WebCam.setObjectName("WebCam")
        self.WebCam.setChecked(True)

        #Video Option
        self.Video = QtWidgets.QRadioButton(self.centralwidget)
        self.Video.setGeometry(QtCore.QRect(240, 160, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.Video.setFont(font)
        self.Video.setObjectName("Video")

        #Social Distance Detector Title
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(70, 0, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")

        #Height input box
        self.HeightIn = QtWidgets.QLineEdit(self.centralwidget)
        self.HeightIn.setGeometry(QtCore.QRect(10, 170, 113, 20))
        self.HeightIn.setObjectName("HeightIn")

        #Angle Input Box
        self.AngleIn = QtWidgets.QLineEdit(self.centralwidget)
        self.AngleIn.setGeometry(QtCore.QRect(10, 220, 113, 20))
        self.AngleIn.setObjectName("AngleIn")

        #Field of View Input Box
        self.FOVIn = QtWidgets.QLineEdit(self.centralwidget)
        self.FOVIn.setGeometry(QtCore.QRect(10, 270, 113, 20))
        self.FOVIn.setObjectName("FOVIn")

        #Required Input Title
        self.ReqiuredIn = QtWidgets.QLabel(self.centralwidget)
        self.ReqiuredIn.setGeometry(QtCore.QRect(10, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.ReqiuredIn.setFont(font)
        self.ReqiuredIn.setObjectName("ReqiuredIn")

        #Height Title
        self.HeightTitle = QtWidgets.QLabel(self.centralwidget)
        self.HeightTitle.setGeometry(QtCore.QRect(10, 150, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.HeightTitle.setFont(font)
        self.HeightTitle.setObjectName("HeightTitle")

        #Angle Title
        self.AngleTitle = QtWidgets.QLabel(self.centralwidget)
        self.AngleTitle.setGeometry(QtCore.QRect(10, 200, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.AngleTitle.setFont(font)
        self.AngleTitle.setObjectName("AngleTitle")

        #Field of View Title
        self.FOVTitle = QtWidgets.QLabel(self.centralwidget)
        self.FOVTitle.setGeometry(QtCore.QRect(10, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.FOVTitle.setFont(font)
        self.FOVTitle.setObjectName("FOVTitle")

        #Distance Options title
        self.DistanceTitle = QtWidgets.QLabel(self.centralwidget)
        self.DistanceTitle.setGeometry(QtCore.QRect(240, 220, 131, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.DistanceTitle.setFont(font)
        self.DistanceTitle.setObjectName("DistanceTitle")

        #Audio Alert Check Box
        self.AudioCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.AudioCheck.setGeometry(QtCore.QRect(240, 250, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.AudioCheck.setFont(font)
        self.AudioCheck.setObjectName("AudioCheck")

        #Screen Shot Check Box
        self.ScreenCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenCheck.setGeometry(QtCore.QRect(240, 280, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.ScreenCheck.setFont(font)
        self.ScreenCheck.setObjectName("ScreenCheck")

        #Start Button
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(140, 320, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.StartButton.clicked.connect(self.show_popup)

        #MenuBar and Menu functions - might delete
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.menuFIle.addAction(self.actionExit)
        self.menubar.addAction(self.menuFIle.menuAction())

        # Main Window call connection. See retranslateUi function below
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ChooseTitle.setText(_translate("MainWindow", "Choose One"))
        self.WebCam.setText(_translate("MainWindow", "Webcam (Default)"))
        self.Video.setText(_translate("MainWindow", "Video"))
        self.Title.setText(_translate("MainWindow", "Social Distance Detector"))
        self.ReqiuredIn.setText(_translate("MainWindow", "Required Input"))
        self.HeightTitle.setText(_translate("MainWindow", "Height (feet)"))
        self.AngleTitle.setText(_translate("MainWindow", "Angle (Degree)"))
        self.FOVTitle.setText(_translate("MainWindow", "Field Of View"))
        self.DistanceTitle.setText(_translate("MainWindow", "Distance Options"))
        self.AudioCheck.setText(_translate("MainWindow", " Audio Alert"))
        self.ScreenCheck.setText(_translate("MainWindow", "Screen Shots"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit The Program"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))

    def show_popup(self):
        msg = QMessageBox()
        height = 0
        angle = 0
        fov = 0

        #If a value is entered, put it into correspounding value
        #If no value entered make it a value of -1
        if (not (bool(self.HeightIn.text())) or not(self.HeightIn.text().isnumeric())):
            height = -1
        else:
            height = int(self.HeightIn.text())
        if (not bool(self.AngleIn.text()) or not(self.AngleIn.text().isnumeric())):
            angle = -1
        else:
            angle = int(self.AngleIn.text())
        if (not bool(self.FOVIn.text()) or not(self.FOVIn.text().isnumeric())):
            fov = -1
        else:
            fov = int(self.FOVIn.text())

        #If a INVLAID value throw a pop up error message
        #Else link code below
        if(height < 0 or height > 200 or angle < 0 or angle > 359
         or fov < 0 or fov > 100):
            msg.setWindowTitle("ERROR")
            msg.setText("Invalid value(s) entered")
            msg.setIcon(QMessageBox.Critical)
            msg.setDetailedText("All values must be numbers and cannot be empty\n\nHeight must be in the range 0 to 200 feet\n\nAngle must be in the range 0 to 359 degrees\n\nField of View must be in the range 0 to 100")
        else:
            msg.setWindowTitle("Link rest of code here")
            msg.setText("Link the code here")
            msg.setIcon(QMessageBox.Information)

        # Will be moved inside of if statement but for now leave here
        x = msg.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
